MadLibs_Name = input("Enter in a name. ")
MadLibs_Adjective = input("Enter in an adjective ending with -est. ")
MadLibs_Verb = input("Enter in a movement verb ending in -ing. ")
MadLibs_City = input("Enter in the name of a city in the U.S. ")
MadLibs_Sport = input("Enter in the name of a sport. ")
MadLibs_Number = input("Enter in a random number from 250-600. ")
print("There was once a boy named " + MadLibs_Name + ".")
print("He traveled the world learning of different cultures and preparing a new invention for the " + MadLibs_Adjective + " World Fair in history. \n \t \"Hello, there!\" called a man, " + MadLibs_Verb + " towards the young boy.")
print("The man was a representative of " + MadLibs_City + " where the fair was being held. He invited " + MadLibs_Name + " to look around. As he did, he noticed many things about the wonderous city. Small children played " + MadLibs_Sport + " and there were at least " + MadLibs_Number + " stalls for food alone.")